WITH DupCheckCodes (CheckCode)
AS (
	SELECT CASE CHARINDEX(' ', n.COMPANY, 1)
			WHEN 0
				THEN n.COMPANY
			ELSE SUBSTRING(n.COMPANY, 1, CHARINDEX(' ', n.COMPANY, 1) - 1)
			END + CASE CHARINDEX(' ', na.ADDRESS_1, 1)
			WHEN 0
				THEN na.ADDRESS_1
			ELSE SUBSTRING(na.ADDRESS_1, 1, CHARINDEX(' ', na.ADDRESS_1, 1) - 1)
			END + CASE CHARINDEX(' ', na.CITY, 1)
			WHEN 0
				THEN na.CITY
			ELSE SUBSTRING(na.CITY, 1, CHARINDEX(' ', na.CITY, 1) - 1)
			END + LEFT(na.ZIP, 5) AS MatchCode
	FROM NAME n
	INNER JOIN Name_Address na ON n.ID = na.ID
	WHERE COMPANY_RECORD = 1
		AND na.PREFERRED_MAIL = 1
		AND na.COUNTRY = 'United States'
		-- AND n.ID LIKE '___3___'
		AND na.ADDRESS_1 NOT LIKE '1500 Spring Garden%'
	GROUP BY CASE CHARINDEX(' ', n.COMPANY, 1)
			WHEN 0
				THEN n.COMPANY
			ELSE SUBSTRING(n.COMPANY, 1, CHARINDEX(' ', n.COMPANY, 1) - 1)
			END + CASE CHARINDEX(' ', na.ADDRESS_1, 1)
			WHEN 0
				THEN na.ADDRESS_1
			ELSE SUBSTRING(na.ADDRESS_1, 1, CHARINDEX(' ', na.ADDRESS_1, 1) - 1)
			END + CASE CHARINDEX(' ', na.CITY, 1)
			WHEN 0
				THEN na.CITY
			ELSE SUBSTRING(na.CITY, 1, CHARINDEX(' ', na.CITY, 1) - 1)
			END + LEFT(na.ZIP, 5)
	HAVING COUNT(*) > 1
	)
SELECT n.ID
	,n.COMPANY
	,na.ADDRESS_1
	,na.ADDRESS_2
	,na.ADDRESS_3
	,na.CITY
	,na.STATE_PROVINCE
	,na.ZIP
	,na.COUNTRY
FROM NAME n
INNER JOIN Name_Address na ON n.ID = na.ID
WHERE COMPANY_RECORD = 1
	AND na.PREFERRED_MAIL = 1
	AND na.COUNTRY = 'United States'
	AND CASE CHARINDEX(' ', n.COMPANY, 1)
		WHEN 0
			THEN n.COMPANY
		ELSE SUBSTRING(n.COMPANY, 1, CHARINDEX(' ', n.COMPANY, 1) - 1)
		END + CASE CHARINDEX(' ', na.ADDRESS_1, 1)
		WHEN 0
			THEN na.ADDRESS_1
		ELSE SUBSTRING(na.ADDRESS_1, 1, CHARINDEX(' ', na.ADDRESS_1, 1) - 1)
		END + CASE CHARINDEX(' ', na.CITY, 1)
		WHEN 0
			THEN na.CITY
		ELSE SUBSTRING(na.CITY, 1, CHARINDEX(' ', na.CITY, 1) - 1)
		END + LEFT(na.ZIP, 5) IN (
		SELECT CheckCode
		FROM DupCheckCodes
		)
ORDER BY na.ADDRESS_1
