SELECT n.COMPANY
	,n.LAST_NAME
	,n.FIRST_NAME
	,na.ADDRESS_1
	,na.ADDRESS_2
	,na.ADDRESS_3
	,na.CITY
	,na.STATE_PROVINCE
	,na.ZIP
	,na.COUNTRY
FROM NAME n
INNER JOIN Name_Address na ON n.ID = na.ID
WHERE n.COMPANY <> ''
	AND n.LAST_NAME = ''
	AND n.COMPANY_RECORD = 0
	and na.PREFERRED_MAIL = 1
ORDER BY n.COMPANY
