BEGIN TRANSACTION

UPDATE d
SET LICENSE_SPLTY = t.DEMOGRAPHICS_LICENSE_SPLTY
FROM dba..Ticket_20150525_001 t
INNER JOIN Demographics d ON t.ID = d.ID
WHERE t.DEMOGRAPHICS_LICENSE_SPLTY IS NOT NULL
	-- ROLLBACK
	-- COMMIT
