BEGIN TRANSACTION

UPDATE dimPopulation
SET AttendedEvent = 'Last Year'
WHERE iMISID IN (
		SELECT DISTINCT ID
		FROM SHMSQL03.SHM_iMIS.dbo.vBoCsActivity
		WHERE activityType = 'MEETING'
			AND TransactionDate BETWEEN CONVERT(VARCHAR(25), DATEADD(YEAR, DATEDIFF(YEAR, 0, DATEADD(YEAR, - 1, GETDATE())), 0), 101) -- First day of last year
				AND CONVERT(VARCHAR(25), DATEADD(MILLISECOND, - 3, DATEADD(YEAR, DATEDIFF(YEAR, 0, DATEADD(YEAR, - 1, GETDATE())) + 1, 0)), 101) -- Last day of last year
		)
	AND LoadDate = CONVERT(VARCHAR(8), GETDATE(), 112)
	-- ROLLBACK
	-- COMMIT
